### ISSUE TITLE
Holap!

### ISSUE THREAD

**Issue by MiguhRuiz** [Zerquix18/TrackYourPenguin#1]
Hola Zerquix!

Espero que te acuerdes de mi, vi que estás actualizando TrackYourPenguin y quería ayudarte.
Cree una guía para instalarlo en cualquier servidor que se pueda acceder con SSH, si no la quieres, puedes borrarla.

Espero que todo te vaya bien, saludos!

**Comment by Zerquix18** [comment]
Hey, claro que me acuerdo de ti. He estado leyendo la guía y le he aplicado unas cuantas mejoras. Muchas gracias! :smile:

**Comment by MiguhRuiz** [comment]
Genial!
