### ISSUE TITLE
Random Errors

### ISSUE THREAD

**Issue by jonathonyoungquist** [Zerquix18/TrackYourPenguin#3]
Simply just load up the site and play with it for a bit. You're going to find random error messages spread without.

**Comment by Zerquix18** [comment]
Can you please send some screenshots? I may fix them.

**Comment by jonathonyoungquist** [comment]
Sure. It's pretty much just this and the twitter deletion thing. :)

![6d25713a6d8220beea32518b578c591b](https://cloud.githubusercontent.com/assets/8397827/12282626/0e2bc1fe-b965-11e5-8ed8-5bece7f7b3dd.png)
![9ea66702321e1f0731037c16fe155d2d](https://cloud.githubusercontent.com/assets/8397827/12282629/0e2e5fcc-b965-11e5-9669-864b1cb9d5e8.png)
![19dce0b6f9e408c52c57983d1ff54a2c](https://cloud.githubusercontent.com/assets/8397827/12282628/0e2e13fa-b965-11e5-99c4-9623de77a48a.png)
![b7e08d8cdae0dd674dfaeaf37132d039](https://cloud.githubusercontent.com/assets/8397827/12282625/0e2ac98e-b965-11e5-8f19-1c21e1275a59.png)
![bc267ec4407bd99e3ec559477fd45103](https://cloud.githubusercontent.com/assets/8397827/12282627/0e2dec9a-b965-11e5-83f3-1bbb60d447a2.png)
![d80fe67a86b1bc10aaa78910664c758d](https://cloud.githubusercontent.com/assets/8397827/12282630/0e311820-b965-11e5-8638-5022395d5232.png)
![e803323f571dfef22c8c9876a525e795](https://cloud.githubusercontent.com/assets/8397827/12282631/0e3a7adc-b965-11e5-8812-f04e7374ec75.png)

**Comment by Zerquix18** [comment]
Hmm, it seems like the webpage that provides the geolocation for IP addresses changed something in their result. I'll be checking that soon. After fixing it, you'll receive a notification to update. Thanks you!
