### ISSUE TITLE
BROKE

### ISSUE THREAD

**Issue by ghost** [Zerquix18/TrackYourPenguin#5]
PLEASE UPDATE ADD NEW FIX AND ADD NEW!!

**Comment by Zerquix18** [comment]
What's wrong with that?

**Comment by ghost** [comment]
ERRORS NEW THEME!! NEW THEME!!

**Comment by ghost** [comment]
ERRORS ON PAGE!!!! TWITTER!

**Comment by ghost** [comment]
PLS

**Comment by Zerquix18** [comment]
Can you please show an screnshot?

**Comment by ghost** [comment]
Notice: Undefined property: stdClass::$geoplugin_status in C:\xampp\htdocs\tracker\typ-inc\hora.php on line 56

CANT DELETE TWEETS TOO!!!!

**Comment by ghost** [comment]
PLEASE!!

**Comment by Zerquix18** [comment]
I'll check it

**Comment by ghost** [comment]
DID FIX??

**Comment by ghost** [comment]
FIX??

**Comment by ghost** [comment]
!!!

**Comment by Zerquix18** [comment]
Fixed. :smile:
